
version: 2

models:
  - name: customers
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null

  - name: stg_customers
    description: '{{doc("table_events")}}'
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  
  - name: stg_orders
    description: >
      testing staging stg_orders
      multiple lines
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id